### ISSUE TITLE
Thanos_query --store parameter 

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/thanos-boshrelease#1]
I have a small discuss according to --cluster.peers with Bartek Płotka https://github.com/improbable-eng/thanos/issues/520 he recommended to Remove all peer flags configuration as i know gossip in plan to remove. https://github.com/improbable-eng/thanos/blob/master/docs/proposals/gossip-removal.md  

> Bartek Płotka  - Let's not duplicate discovery mechanisms. The key here is to avoid gossip (since it will be removed soon) - and just configure your thanos-queriers (both of them) with :
```
 --store=<thanos-sidecar>:<grpc-port>
 --store=<thanos-sidecar2>:<grpc-port>
 --store=<thanos-store>:<grpc-port> ...
```
P.S also create thanos bosh release, privately, 2 weeks ago =) facepalm =)))) already update it to new thanos version v0.1.0  https://github.com/improbable-eng/thanos/releases

**Comment by poblin-orange** [comment]
given the speed of evolution, we have tried to extend prometheus bosh release with docker bosh release + thanos stock docker image.
Here is our config, if it helps https://github.com/orange-cloudfoundry/paas-templates/blob/manual-drop/master-depls/prometheus/template/add-thanos-sidecar-operators.yml
